const ACTION_TYPES = {
  REGISTER_SERVICE: "REGISTER_SERVICE",
  GET_SERVICES: "GET_SERVICES",
  GET_SERVICE_BY_ID: "GET_SERVICE_BY_ID",
  ADD_RELEASE: "ADD_RELEASE",
  RETRY_RELEASE: "RETRY_RELEASE",
};

export default ACTION_TYPES;
