version: 1.0.0
title: Application should be operational even if a pod is terminated?
description: If an instance of the application is terminated, the applications as a whole should still be operational.
tags:
- k8s
- pod
- http
steady-state-hypothesis:
    title: The app is healthy
    probes:
    - name: app-respnds-to-requests
      type: probe
      tolerance: 200
      provider:
        type: http
        timeout: 3
        verify_tls: false
        url: ${HOST_URL}
        headers:
            host: default.acme.com 
method:
- type: action
  name: terminate-pod
  provider:
    type: python
    module: chaosk8s.pod.actions
    func: terminate_pods
    arguments:
        name_pattern: ${POD_NAME}
  pauses:
    after: 2