const ACTION_TYPES = {
  REGISTER_USER: "REGISTER_USER",
  LOGIN_USER: "LOGIN_USER",
  UPDATE_USER: "UPDATE_USER",
  GET_USER_DETAILS: "GET_USER_DETAILS",
  LOGIN_CLUSTER: "LOGIN_CLUSTER",
  INSTALL_ISTIO: "INSTALL_ISTIO",
  UNINSTALL_ISTIO: "UNINSTALL_ISTIO",
  COFIGURE_PROMETHEUS: "COFIGURE_PROMETHEUS",
};

export default ACTION_TYPES;
