const ACTION_TYPES = {
  REGISTER_USER: "REGISTER_USER",
  LOGIN_USER: "LOGIN_USER",
  UPDATE_USER: "UPDATE_USER",
  GET_USER_DETAILS: "GET_USER_DETAILS",
  LOGIN_CLUSTER: "LOGIN_CLUSTER",
};

export default ACTION_TYPES;
