const ACTION_TYPES = {
  GET_PREDICTED_CPU_TIME_SERIES_DATA_BY_POD:
    "GET_PREDICTED_CPU_TIME_SERIES_DATA_BY_POD",
  GET_PREDICTED_MEMORY_TIME_SERIES_DATA_BY_POD:
    "GET_PREDICTED_MEMORY_TIME_SERIES_DATA_BY_POD",
  GET_PREDICTED_NETWORK_TIME_SERIES_DATA_BY_POD:
    "GET_PREDICTED_NETWORK_TIME_SERIES_DATA_BY_POD",
};

export default ACTION_TYPES;
