from .database_router import router as DatabaseRouter
from .cpu_prediction_router import router as CPUPredictionRouter
from .centrality_prediction_router import router as CentralityPredictionRouter
from .prediction_provider_router import router as PredictionProviderRouter