const ACTION_TYPES = {
  GET_POD_DETAILS_BY_NAMESPACE: "GET_POD_DETAILS_BY_NAMESPACE",
  GET_SERVICES_DETAILS_BY_NAMESPACE: "GET_SERVICES_DETAILS_BY_NAMESPACE",
  GET_DEPENDENCY_DETAILS_BY_NAMESPACE: "GET_DEPENDENCY_DETAILS_BY_NAMESPACE",
  CLUSTER_CONNECTED: "CLUSTER_CONNECTED",
  CLUSTERIPS_AND_LOADBALANCES: "CLUSTERIPS_AND_LOADBALANCES",
};

export default ACTION_TYPES;
