const ACTION_TYPES = {
    GET_CPU_TIME_SERIES_DATA: "GET_CPU_TIME_SERIES_DATA",
    GET_CPU_TIME_SERIES_DATA_BY_POD: "GET_CPU_TIME_SERIES_DATA_BY_POD",
    GET_MEMORY_TIME_SERIES_DATA: "GET_MEMORY_TIME_SERIES_DATA",
    GET_MEMORY_TIME_SERIES_DATA_BY_POD: "GET_MEMORY_TIME_SERIES_DATA_BY_POD",
}

export default ACTION_TYPES;